### ISSUE TITLE
Selecting Plant ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by silverware13** [OSU-CS492-W19/final-project-final-project-team-3#10]
Selecting a plant from the list of favorites, or any of the searches can sometimes cause the following crash:

2019-03-17 19:31:31.680 6798-6798/com.example.android.connectedweather E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.connectedweather, PID: 6798
    java.lang.ArrayIndexOutOfBoundsException: length=22; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)
        at com.example.android.usdaplantindex.PlantSearchAdapter$PlantItemViewHolder.onClick(PlantSearchAdapter.java:74)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by silverware13** [comment]
Fixed issue with PlantSearchAdapter allowing Null values.
